【Day 4】
判断语句（要求掌握多条件判断）
循环语句
三目表达式
容器
可迭代对象
迭代器
生成器
--------------------------------------
【作业构想】
学习代码200-300行
请对方输入一个0-9之间的数字，进行检查，若不是数字提示：您输入的不是数字，请输入0-9间的数字，若数字不在0-9范围内，提示用户输入0-9之间的数字，直至用户输入正确。
系统随机生成一个长度为3的数字列表，且列表中元素在0-9之间并且不相等。将用户输入与该列表进行比较，若为列表第一个元素，则荣获第一名，列表第二个元素，则荣获第二名，列表第三个名字，则荣获第三名，否则提示用户未得奖，输入1重新开始游戏，输入2则结束游戏。
注意：每次游戏中列表中数字要求随机生成，每轮游戏都不相等。
-------------------------------------
【作业提交时间】
2019年1月29日24：00
注意：未完成者将会被清退
------------------------------------
【点评】
完成时间：2019年1月30日12：00
注意：未完成竟会被清退

判断语句：
if-else 
判断语句基于某种条件触发，当条件满足的时候，执行特定的操作。

In [1]:
x = 0.5
if x > 0:
    print("这是一个大于0的数")
    
a = 88 
if a < 0:
    print("a < 0") 
elif a < 10:
    print("0<= a < 10")
elif a < 100:
    print("10 <= a < 100")
else:
    print("a > 100")

这是一个大于0的数
10 <= a < 100


循环语句：将一段代码重复多次，主要有while循环和for循环

In [3]:
#循环遍历列表
num = [1,2,3,4]
while num:
    values = num.pop(0)
    print(values)
print('__________') 
#for循环
num = [1,2,3,4]
for c in num:
    print(c)
print('__________') 
a = (5,4,3,2,1)
for i in a:
    print(i)
print('__________')    
b = {1:'one',2:'two',3:'three'}
for k in b:
    print(k,b[k])

1
2
3
4
__________
1
2
3
4
__________
5
4
3
2
1
__________
1 one
2 two
3 three


三目运算符：跟其他语言不一样
其他语言：判段的条件?条件为真时的结果:条件为假时的结果
python：条件为真时的结果 if 判段的条件 else 条件为假时的结果 

In [8]:
a = 0.5
b = 2
h = ""

h = a-b if a>b else a+b

print(h)

2.5


容器：用来存放基本对象或者其他容易对象的一种类型。分为内置容器和自定义容器，内置容器主要是列表，元组，字典，集合，自定义容器为numpy数组。
列表、元组、字典、集合的相关概念和相关方法这里不在赘述，主要粗略的讲一下numpy的自定义数组的生成，后续遇到numpy模块会详细讲解。

In [10]:
import numpy as np

#用列表构造
a = np.array([1,2,3,4])
print(a)
print('-----------')

#用元组构造
b = np.array((1,2,3,4))
print(b)
print('-----------')


#构建一个2*3的二维数组
c = np.array([[1,2,3],
             [4,5,6]])
print(c)
print('-----------')

[1 2 3 4]
-----------
[1 2 3 4]
-----------
[[1 2 3]
 [4 5 6]]
-----------


可迭代对象：
列表、元组、字典、集合

迭代器的主要作用就是支持for循环遍历的操作，使得可迭代对象可以穷尽。

以下是可迭代对象对应的迭代器

In [ ]:
#列表
print([1,2,3]._iter_())
print('--------')
#元组
print((1,2,3)._iter_())
print('--------')
#字典
print({1:1,2:2,3:3}._iter_())
print('--------')
#集合
print({1,2,3}._iter_())
print('--------')

生成器：
生成器是一个特殊的迭代器，使用函数来定义，使用yield关键字返回值。

In [17]:
def test_generator():
    yield 1
    yield 2
g = test_generator()

#python旧版
print(g.next())
print(g._next_())

#python旧版本使用的next（）方法在新版本中已经更名，所有会抛出错误。参考链接：https://blog.csdn.net/gaifuxi9518/article/details/81059938

AttributeError: 'generator' object has no attribute 'next'

In [18]:
def test_generator():
    yield 1
    yield 2
g = test_generator()

#python3.7版本
print(next(g))
print(next(g))

1
2


作业：

In [ ]:
import random
#num = int(input('请输入一个0-9之间的数字：'))

while True:
    num = int(input('请输入一个0-9之间的数字：'))
    if 0 <= num <=9:
        prizeNum = random.sample(range(10),3)
        if num == prizeNum[0]:
            print("恭喜你，获得一等奖！")
        elif num == prizeNum[1]:
            print("恭喜你，获得二等奖！")
        elif num == prizeNum[2]:
            print("恭喜你，获得三等奖！")
        else:
            print("很遗憾，你未中奖")
    else:
        print('请输入一个0-9之间的数字')
    print('再试一次？ 1-继续，2-结束')
    flag = int(input('请输入1或者2：'))
    if flag == 1:
        continue
    else:
        break
